services:
  - type: web
    name: simulateur-cehr
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT app_cehr:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
